'use strict';

module.exports = [
  {
    id: 'adm',
    name: 'Administração',
    emoji: '<:1000079910:1401858796497801347>',
    description: 'Comandos administrativos e de configuração do servidor.',
    commands: [
      {
        name: 'prefix',
        description: 'Altera o prefixo do bot.',
        usage: 'prefix <novo prefixo>',
        permissions: ['Administrator'],
        details: 'O prefixo define como os comandos são reconhecidos no servidor.',
        id: '000000000000000001',
      },
      {
        name: 'addemoji',
        description: 'Adiciona um emoji ao servidor.',
        usage: 'addemoji <URL> [nome]',
        permissions: ['ManageEmojisAndStickers'],
        details: 'Você pode usar um emoji de outro servidor ou uma URL de imagem válida.',
        id: '000000000000000002',
      },
      {
        name: 'copyemoji',
        description: 'Copia um emoji de outro servidor.',
        usage: 'copyemoji <emoji>',
        permissions: ['ManageEmojisAndStickers'],
        details: 'Ideal para importar emojis personalizados com rapidez.',
        id: '000000000000000003',
      },
      {
        name: 'backup',
        description: 'Cria um backup do servidor.',
        usage: 'backup',
        permissions: ['Administrator'],
        details: 'O backup salva canais, cargos, configurações e permissões.',
        id: '000000000000000004',
      },
      {
        name: 'restore',
        description: 'Restaura o backup do servidor.',
        usage: 'restore <ID>',
        permissions: ['Administrator'],
        details: 'Tenha cuidado! Isso sobrescreverá a estrutura atual.',
        id: '000000000000000005',
      },
      {
        name: 'addroles',
        description: 'Adiciona múltiplos cargos a um usuário de uma vez.',
        usage: 'addroles <@usuário> <@cargo1> [@cargo2] ...',
        permissions: ['ManageRoles'],
        details: 'Útil para atribuir vários cargos rapidamente.',
        id: '000000000000000006',
      },
      {
        name: 'removeroles',
        description: 'Remove todos os cargos de um usuário (exceto o cargo padrão).',
        usage: 'removeroles <@usuário>',
        permissions: ['ManageRoles'],
        details: 'Remove todos os cargos personalizados atribuídos a um usuário.',
        id: '000000000000000007',
      },
      {
        name: 'setlog',
        description: 'Define o canal de logs.',
        usage: 'setlog <#canal>',
        permissions: ['ManageGuild'],
        details: 'O canal será usado para registrar ações de moderação e sistema.',
        id: '000000000000000008',
      },
    ],
  },
  {
    id: 'mod',
    name: 'Moderação',
    emoji: '<:1000079908:1401856703162482768>',
    description: 'Ferramentas para moderação de usuários e canais.',
    commands: [
      {
        name: 'ban',
        description: 'Bane um usuário do servidor.',
        usage: 'ban <@usuário> [motivo]',
        permissions: ['BanMembers'],
        id: '000000000000000009',
      },
      {
        name: 'unban',
        description: 'Desbane um usuário.',
        usage: 'unban <ID do usuário>',
        permissions: ['BanMembers'],
        id: '000000000000000010',
      },
      {
        name: 'kick',
        description: 'Expulsa um usuário do servidor.',
        usage: 'kick <@usuário> [motivo]',
        permissions: ['KickMembers'],
        id: '000000000000000011',
      },
      {
        name: 'mute',
        description: 'Silencia um usuário.',
        usage: 'mute <@usuário> <tempo> [motivo]',
        permissions: ['ModerateMembers'],
        id: '000000000000000012',
      },
      {
        name: 'unmute',
        description: 'Remove o silêncio de um usuário.',
        usage: 'unmute <@usuário>',
        permissions: ['ModerateMembers'],
        id: '000000000000000013',
      },
      {
        name: 'clear',
        description: 'Limpa mensagens de um canal.',
        usage: 'clear <quantidade>',
        permissions: ['ManageMessages'],
        id: '000000000000000014',
      },
      {
        name: 'lock',
        description: 'Trava um canal para todos.',
        usage: 'lock',
        permissions: ['ManageChannels'],
        id: '000000000000000015',
      },
      {
        name: 'unlock',
        description: 'Destrava um canal.',
        usage: 'unlock',
        permissions: ['ManageChannels'],
        id: '000000000000000016',
      },
      {
        name: 'lockuser',
        description: 'Impede um usuário de enviar mensagens.',
        usage: 'lockuser <@usuário>',
        permissions: ['ManageRoles'],
        id: '000000000000000017',
      },
      {
        name: 'unlockuser',
        description: 'Libera um usuário silenciado.',
        usage: 'unlockuser <@usuário>',
        permissions: ['ManageRoles'],
        id: '000000000000000018',
      },
      {
        name: 'send',
        description: 'Envia uma mensagem como o bot.',
        usage: 'send <mensagem>',
        permissions: ['Administrator'],
        id: '000000000000000019',
      },
      {
        name: 'slowmode',
        description: 'Define o modo lento em um canal.',
        usage: 'slowmode <tempo>',
        permissions: ['ManageChannels'],
        id: '000000000000000020',
      },
    ],
  },
  {
    id: 'info',
    name: 'Informações',
    emoji: '<:1000079907:1401856353756119060>',
    description: 'Comandos para exibir informações.',
    commands: [
      {
        name: 'avatar',
        description: 'Exibe o avatar de um usuário.',
        usage: 'avatar [@usuário]',
        permissions: [],
        id: '000000000000000021',
      },
      {
        name: 'botinfo',
        description: 'Informações sobre o bot.',
        usage: 'botinfo',
        permissions: [],
        id: '000000000000000022',
      },
      {
        name: 'ping',
        description: 'Exibe a latência do bot.',
        usage: 'ping',
        permissions: [],
        id: '000000000000000023',
      },
      {
        name: 'stats',
        description: 'Estatísticas do bot.',
        usage: 'stats',
        permissions: [],
        id: '000000000000000024',
      },
      {
        name: 'userinfo',
        description: 'Exibe informações de um usuário.',
        usage: 'userinfo [@usuário]',
        permissions: [],
        id: '000000000000000025',
      },
    ],
  },
  {
    id: 'util',
    name: 'Utilitários',
    emoji: '<:1000079906:1401856203457433642>',
    description: 'Utilitários gerais para o servidor.',
    commands: [
      {
        name: 'doar',
        description: 'Faça uma doação para apoiar o desenvolvimento do bot.',
        usage: 'doar <valor>',
        permissions: [],
        details: 'Você será redirecionado para a página de pagamento.',
        id: '000000000000000026',
      },
      {
        name: 'privacy',
        description: 'Mostra a política de privacidade.',
        usage: 'privacy',
        permissions: [],
        details: 'Mostra como os seus dados são usados pelo bot.',
        id: '000000000000000027',
      },
      {
        name: 't',
        description: 'Traduz um texto.',
        usage: 't <texto>',
        permissions: [],
        details: 'Você também pode especificar o idioma com `t en Olá`.',
        id: '000000000000000028',
      },
    ],
  },
  {
    id: 'giveaway',
    name: 'Sorteios',
    emoji: '<:1000079905:1401855859532890202>',
    description: 'Gerenciamento de sorteios no servidor.',
    commands: [
      {
        name: 'sorteio',
        description: 'Inicia um novo sorteio.',
        usage: 'sorteio "<prêmio>" <vencedores> <tempo> <#canal>',
        permissions: ['ManageMessages'],
        id: '000000000000000029',
      },
      {
        name: 'rerolar',
        description: 'Escolhe um novo vencedor.',
        usage: 'rerolar <ID>',
        permissions: ['ManageMessages'],
        id: '000000000000000030',
      },
      {
        name: 'cancelar',
        description: 'Cancela um sorteio em andamento.',
        usage: 'cancelar <ID>',
        permissions: ['ManageMessages'],
        id: '000000000000000031',
      },
    ],
  },
];
