'use strict';

module.exports = [
  {
    id: 'adm',
    name: 'Administração',
    description: 'Comandos administrativos e de configuração do servidor.',
    commands: [
      {
        name: 'prefix',
        description: 'Altera o prefixo do bot.',
        usage: 'prefix <novo prefixo>',
        permissions: ['Administrator'],
        details: 'O prefixo define como os comandos são reconhecidos no servidor.',
        id: '000000000000000005',
      },
      {
        name: 'addemoji',
        description: 'Adiciona um emoji ao servidor.',
        usage: 'addemoji <URL|emoji> [nome]',
        permissions: ['ManageEmojisAndStickers'],
        details: 'Você pode usar um emoji de outro servidor ou uma URL de imagem válida.',
        id: '000000000000000011',
      },
      {
        name: 'copyemoji',
        description: 'Copia um emoji de outro servidor.',
        usage: 'copyemoji <emoji>',
        permissions: ['ManageEmojisAndStickers'],
        details: 'Ideal para importar emojis personalizados com rapidez.',
        id: '000000000000000013',
      },
      {
        name: 'backup',
        description: 'Cria um backup do servidor.',
        usage: 'backup',
        permissions: ['Administrator'],
        details: 'O backup salva canais, cargos, configurações e permissões.',
        id: '000000000000000012',
      },
      {
        name: 'restore',
        description: 'Restaura o backup do servidor.',
        usage: 'restore <ID>',
        permissions: ['Administrator'],
        details: 'Tenha cuidado! Isso sobrescreverá a estrutura atual.',
        id: '000000000000000015',
      },
      {
        name: 'setlog',
        description: 'Define o canal de logs.',
        usage: 'setlog <#canal>',
        permissions: ['ManageGuild'],
        details: 'O canal será usado para registrar ações de moderação e sistema.',
        id: '000000000000000016',
      },
    ],
  },
  {
    id: 'mod',
    name: 'Moderação',
    description: 'Ferramentas para moderação de usuários e canais.',
    commands: [
      {
        name: 'ban',
        description: 'Bane um usuário do servidor.',
        usage: 'ban <@usuário> [motivo]',
        permissions: ['BanMembers'],
        id: '000000000000000001',
      },
      {
        name: 'unban',
        description: 'Desbane um usuário.',
        usage: 'unban <ID do usuário>',
        permissions: ['BanMembers'],
        id: '000000000000000023',
      },
      {
        name: 'kick',
        description: 'Expulsa um usuário do servidor.',
        usage: 'kick <@usuário> [motivo]',
        permissions: ['KickMembers'],
        id: '000000000000000002',
      },
      {
        name: 'mute',
        description: 'Silencia um usuário.',
        usage: 'mute <@usuário> <tempo> [motivo]',
        permissions: ['ModerateMembers'],
        id: '000000000000000020',
      },
      {
        name: 'unmute',
        description: 'Remove o silêncio de um usuário.',
        usage: 'unmute <@usuário>',
        permissions: ['ModerateMembers'],
        id: '000000000000000026',
      },
      {
        name: 'clear',
        description: 'Limpa mensagens de um canal.',
        usage: 'clear <quantidade>',
        permissions: ['ManageMessages'],
        id: '000000000000000017',
      },
      {
        name: 'lock',
        description: 'Trava um canal para todos.',
        usage: 'lock',
        permissions: ['ManageChannels'],
        id: '000000000000000018',
      },
      {
        name: 'unlock',
        description: 'Destrava um canal.',
        usage: 'unlock',
        permissions: ['ManageChannels'],
        id: '000000000000000024',
      },
      {
        name: 'lockuser',
        description: 'Impede um usuário de enviar mensagens.',
        usage: 'lockuser <@usuário>',
        permissions: ['ManageRoles'],
        id: '000000000000000019',
      },
      {
        name: 'unlockuser',
        description: 'Libera um usuário silenciado.',
        usage: 'unlockuser <@usuário>',
        permissions: ['ManageRoles'],
        id: '000000000000000025',
      },
      {
        name: 'send',
        description: 'Envia uma mensagem como o bot.',
        usage: 'send <mensagem>',
        permissions: ['Administrator'],
        id: '000000000000000021',
      },
      {
        name: 'slowmode',
        description: 'Define o modo lento em um canal.',
        usage: 'slowmode <tempo>',
        permissions: ['ManageChannels'],
        id: '000000000000000022',
      },
    ],
  },
  {
    id: 'info',
    name: 'Informações',
    description: 'Comandos para exibir informações.',
    commands: [
      {
        name: 'avatar',
        description: 'Exibe o avatar de um usuário.',
        usage: 'avatar [@usuário]',
        permissions: [],
        id: '000000000000000027',
      },
      {
        name: 'botinfo',
        description: 'Informações sobre o bot.',
        usage: 'botinfo',
        permissions: [],
        id: '000000000000000028',
      },
      {
        name: 'ping',
        description: 'Exibe a latência do bot.',
        usage: 'ping',
        permissions: [],
        id: '000000000000000030',
      },
      {
        name: 'stats',
        description: 'Estatísticas do bot.',
        usage: 'stats',
        permissions: [],
        id: '000000000000000031',
      },
      {
        name: 'userinfo',
        description: 'Exibe informações de um usuário.',
        usage: 'userinfo [@usuário]',
        permissions: [],
        id: '000000000000000003',
      },
    ],
  },
  {
    id: 'util',
    name: 'Utilitários',
    description: 'Utilitários gerais para o servidor.',
    commands: [
      {
        name: 'privacy',
        description: 'Mostra a política de privacidade.',
        usage: 'privacy',
        permissions: [],
        id: '000000000000000032',
      },
      {
        name: 't',
        description: 'Traduz um texto.',
        usage: 't <texto>',
        permissions: [],
        details: 'Você também pode especificar o idioma com `t en Olá`.',
        id: '000000000000000033',
      },
    ],
  },
  {
    id: 'giveaway',
    name: 'Giveaway',
    description: 'Gerenciamento de sorteios no servidor.',
    commands: [
      {
        name: 'sorteio',
        description: 'Inicia um novo sorteio.',
        usage: 'sorteio <"prêmio"> <vencedores> <tempo> <#canal>',
        permissions: ['ManageMessages'],
        id: '000000000000000035',
      },
      {
        name: 'rerolar',
        description: 'Escolhe um novo vencedor.',
        usage: 'rerolar <ID>',
        permissions: ['ManageMessages'],
        id: '000000000000000036',
      },
      {
        name: 'cancelar',
        description: 'Cancela um sorteio em andamento.',
        usage: 'cancelar <ID>',
        permissions: ['ManageMessages'],
        id: '000000000000000034',
      },
      
    ],
  },
];
